CREATE DATABASE SP_MEDICAL_GROUP
GO

USE SP_MEDICAL_GROUP
GO

CREATE TABLE CLINICA
(
IdClinica INT PRIMARY KEY IDENTITY,
NomeClinica VARCHAR (50) NOT NULL,
Cnpj INT NOT NULL,
RazaoSocial VARCHAR (50) NOT NULL,
Endereço VARCHAR (50) NOT NULL,
)
GO

DROP TABLE CLINICA
GO


SELECT * FROM CLINICA
GO

CREATE TABLE TipoUsuario
(
IdTipoUsuario INT PRIMARY KEY IDENTITY,
NomeTipo VARCHAR (40) NOT NULL
)
GO

SELECT * FROM TipoUsuario
GO

CREATE TABLE USUARIO
(
IdUsuario INT PRIMARY KEY IDENTITY,
IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
Email VARCHAR (50) NOT NULL,
Senha VARCHAR (20) NOT NULL
)
GO

SELECT * FROM USUARIO
GO

CREATE TABLE ESPECIALIDADE 
(
IdEspecialidade INT PRIMARY KEY IDENTITY,
NomeEspecialidade VARCHAR (40) NOT NULL
)
GO

SELECT * FROM ESPECIALIDADE
GO

CREATE TABLE MEDICO 
(
IdMedico INT PRIMARY KEY IDENTITY,
IdEspecialidade INT FOREIGN KEY REFERENCES ESPECIALIDADE(IdEspecialidade),
IdClinica INT FOREIGN KEY REFERENCES CLINICA(IdClinica),
IdUsuario INT FOREIGN KEY REFERENCES USUARIO(IdUsuario),
Crm VARCHAR NOT NULL,
NomeMedico VARCHAR (40) NOT NULL
)
GO

DROP TABLE MEDICO
GO

SELECT * FROM MEDICO
GO

CREATE TABLE SITUACAO 
(
IdSituacao INT PRIMARY KEY IDENTITY,
TipoSituacao VARCHAR (20) NOT NULL
)
GO

SELECT * FROM SITUACAO
GO

CREATE TABLE PACIENTE 
(
IdPaciente INT PRIMARY KEY IDENTITY,
IdUsuario INT FOREIGN KEY REFERENCES USUARIO(IdUsuario),
NomePaciente VARCHAR (40) NOT NULL,
DataNascimento DATETIME NOT NULL,
Telefone VARCHAR (15),
Rg CHAR (12) UNIQUE NOT NULL,
Cpf CHAR (11) UNIQUE NOT NULL,
Endereco VARCHAR (50) NOT NULL
)
GO

ALTER TABLE PACIENTE
DataNascimento DATETIME TO VARCHAR (50)

DROP TABLE PACIENTE
GO

SELECT * FROM PACIENTE
GO

CREATE TABLE CONSULTA 
(
IdConsulta INT PRIMARY KEY IDENTITY,
IdMedico INT FOREIGN KEY REFERENCES MEDICO(IdMedico),
IdPaciente INT FOREIGN KEY REFERENCES PACIENTE(IdPaciente),
IdSituacao INT FOREIGN KEY REFERENCES SITUACAO(IdSituacao),
Data_Hora DATETIME NOT NULL,
Descrição VARCHAR (100),
)
GO

DROP TABLE CONSULTA
GO

SELECT * FROM CONSULTA
GO