USE SP_MEDICAL_GROUP
GO

SELECT * FROM TipoUsuario
SELECT * FROM SITUACAO
SELECT * FROM ESPECIALIDADE
SELECT * FROM CLINICA
SELECT * FROM USUARIO
SELECT * FROM MEDICO
SELECT * FROM PACIENTE
SELECT * FROM CONSULTA